name: sample
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.23.0
  firebase_auth: ^4.13.0
  # firebase_database: ^10.2.4
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^16.1.0

  #core
  flutter_native_splash: ^2.3.5
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  equatable: ^2.0.5
  build_runner: ^2.4.6
  retrofit: ^4.0.3
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.3
  uuid: ^4.2.1
  url_launcher: ^6.2.1

  # data storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # io:
  file_picker: ^6.1.1
  flutter_svg: ^2.0.9
  image: ^4.0.17
  photo_view: ^0.14.0
  dio: ^5.3.3
  image_picker: ^1.0.4
  pretty_dio_logger: 1.3.1
  flag: ^7.0.0

  # system:
  app_settings: ^5.1.1
  device_info_plus: ^9.1.0
  permission_handler: ^11.0.1
  internet_connection_checker: ^1.0.0+1
  flutter_timezone: ^1.0.8
  flutter_contacts: ^1.1.7+1

  cached_network_image: ^3.3.0
  intl: ^0.18.1
  photo_gallery: ^2.1.1
  shimmer: ^3.0.0
  flutter_image_compress: ^2.1.0
  jwt_decoder: ^2.0.1
  loadmore: ^2.1.0
  logger: ^2.0.2+1
  carousel_slider: ^4.2.1
  geolocator: ^10.1.0
  location: ^5.0.3
  event_bus: ^2.0.0
  path: ^1.8.3
  dynamic_height_grid_view: ^0.0.4
  highlight_text: 1.7.0
  lottie: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_flavorizr: ^2.2.1
  http: ^1.2.0
  timeago: ^3.6.1
  timezone: ^0.9.2
  collection: ^1.18.0
  custom_pop_up_menu: ^1.2.4
  flutter_screenutil: ^5.9.0
  rxdart: ^0.27.7
  get_it: ^7.6.7
  custom_cupertino_picker: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/json/

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash12.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/splash12.png

  android_12:
    image: assets/images/splash12.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icons/app_icon.png" 
  android: true
  ios: true
  remove_alpha_ios: true